services:
  vision-platform:
    build: .
    container_name: smartx-vision-v3
    restart: unless-stopped
    shm_size: '8gb'
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./data:/opt/vision/data
      - ./logs:/opt/vision/logs
      - ./app:/opt/vision/app
      - ./main.py:/opt/vision/main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - vision-net
networks:
  vision-net:
    driver: bridge
